"""Runtime configuration constants."""
from app.core.foundation import DATA_DIR, YARN_DIR, DB_PATH, STATIC_DIR, IMAGE_EXTS, LANGUAGE_CODE_RE, AI_MAX_OUTPUT_TOKENS, AI_SETTING_KEYS, SESSION_COOKIE, CSRF_COOKIE, MAX_SCRAPE_BYTES, GITHUB_RELEASES_URL, GITHUB_RELEASES_HTML, RELEASE_SYNC_INTERVAL_SECONDS, _ALLOWED_ORIGINS

__all__ = [name for name in globals() if not name.startswith("__")]
